server:
    port: 8052
    servlet:
        context-path: /
        encoding:
            charset: UTF-8
            enabled: true
            force: true

spring:
    security:
        user:
            name: admin
            password: 1234
    application:
        name: flix-session
    devtools:
        restart:
            enabled: true

    data:
        redis:
            host: redis
            port: 6379
