spring:
    application:
        name: session
    config:
        import: "configserver:http://localhost:8058"
    cloud:
        config:
            profile: local # 사용할 프로필
            label: main # Git 브랜치 (기본값: main)
